version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - './conf/default.conf:/etc/nginx/conf.d/default.conf'
      - 'media:/app/media'
      - 'static:/app/static'
      - 'dist:/app/client/dist/'
    labels:
      - traefik.backend=datingapp_chat
      - traefik.frontend.rule=Host:chat.monstrofil.xyz
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - internal
      - proxy
    depends_on:
     - redis
    environment: &environment
      # list all envs here and link them in other containers
      C_FORCE_ROOT: 1
      DEV: 1
  redis:
    image: "redis:latest"
    environment: *environment
    networks:
      - internal
  frontend:
    build: .
    command: /bin/bash ./docker-entrypoint.sh
    environment: *environment
    depends_on:
      - redis
    volumes:
      - 'media:/app/media'
      - 'static:/app/static'
      - 'dist:/app/client/dist/'
    networks:
      - internal
volumes:
  media:
  static:
  dist:
networks:
  proxy:
    external: true
  internal:
    external: false