# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-08 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageUpload',
        ),
    ]
