# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-08 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190408_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
    ]
